# Preparacao das tabelas treino e teste

In [10]:
import pandas as pd
import os

## Importando a tabela filtrada no databricks

In [11]:
df = pd.read_csv('./bases/application_train_filtered.csv')
df.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,456162,False,Cash loans,F,False,False,0,112500.0,700830.0,22738.5,...,False,False,False,False,0.0,0.0,0.0,0.0,0.0,1.0
1,134978,False,Cash loans,F,False,False,0,90000.0,375322.5,14422.5,...,False,False,False,False,0.0,0.0,0.0,1.0,0.0,3.0
2,318952,False,Cash loans,M,True,False,0,180000.0,544491.0,16047.0,...,False,False,False,False,0.0,0.0,0.0,1.0,1.0,3.0
3,361264,False,Cash loans,F,False,True,0,270000.0,814041.0,28971.0,...,False,False,False,False,0.0,0.0,0.0,0.0,1.0,4.0
4,260639,False,Cash loans,F,False,True,0,144000.0,675000.0,21906.0,...,False,False,False,False,0.0,0.0,0.0,10.0,0.0,0.0

## Separando em treino e teste

In [12]:
df_treino = df.sample(frac=0.7, random_state=42)
list(df_treino.index)

[161368,
 177644,
 42295,
 161674,
 235457,
 60944,
 207237,
 117818,
 152123,
 104557,
 193292,
 49538,
 69995,
 124113,
 112034,
 9100,
 204778,
 5317,
 103647,
 109058,
 36987,
 214492,
 148823,
 116678,
 14221,
 124727,
 73378,
 109536,
 102604,
 226864,
 201674,
 33148,
 29629,
 203121,
 18094,
 147770,
 3291,
 176586,
 7162,
 55423,
 204733,
 37980,
 214405,
 28486,
 53432,
 187870,
 201794,
 179999,
 245769,
 90535,
 131395,
 59960,
 173627,
 80095,
 6312,
 96104,
 141284,
 49580,
 42538,
 141061,
 197362,
 219547,
 100543,
 100335,
 215559,
 24280,
 1416,
 93058,
 39987,
 140855,
 120576,
 33881,
 21703,
 122045,
 18581,
 164949,
 110245,
 10898,
 231693,
 92582,
 101466,
 85215,
 25553,
 244726,
 42268,
 226471,
 18723,
 243577,
 167145,
 223119,
 204138,
 36340,
 149508,
 238214,
 156244,
 48464,
 34601,
 153264,
 58401,
 112027,
 132573,
 92104,
 38579,
 239177,
 160300,
 144197,
 143341,
 186870,
 69430,
 53136,
 230762,
 236464,
 185436,
 109270,
 64725,
 141912,
 233734,
 195376,
 207148,
 70078,
 77224,
 47091,
 17310,
 97991,
 123807,
 74480,
 162242,
 75435,
 34020,
 244138,
 148488,
 104982,
 4095,
 206477,
 18081,
 144217,
 167545,
 97849,
 84190,
 18015,
 209031,
 206776,
 158257,
 37857,
 38114,
 57192,
 242182,
 22610,
 178347,
 198778,
 172629,
 155896,
 103672,
 77563,
 7802,
 164597,
 54574,
 158148,
 28173,
 241894,
 89699,
 100749,
 233186,
 187845,
 40011,
 53815,
 43979,
 164037,
 39841,
 174502,
 111722,
 236221,
 162431,
 66675,
 184279,
 171109,
 32755,
 16212,
 66409,
 44444,
 220539,
 46060,
 190064,
 68490,
 234585,
 123433,
 6313,
 2316,
 94374,
 32736,
 75873,
 128310,
 155997,
 215144,
 195221,
 165286,
 145010,
 27145,
 91904,
 169655,
 173126,
 196057,
 100046,
 81258,
 187623,
 94746,
 245073,
 41116,
 1543,
 60054,
 218634,
 61335,
 217889,
 42167,
 13307,
 62141,
 18633,
 122579,
 217298,
 134261,
 186119,
 60767,
 183948,
 34958,
 213023,
 224270,
 187260,
 24494,
 88676,
 210738,
 112662,
 99117,
 234200,
 50043,
 66801,
 138637,
 185944,
 103385,
 210868,
 148416,
 180712,
 59769,
 67128,
 90259,
 89085,
 197588,
 162926,
 40421,
 77800,
 180544,
 242014,
 183123,
 146458,
 146260,
 39180,
 142929,
 110589,
 192712,
 134233,
 161381,
 72700,
 119105,
 196280,
 24786,
 45497,
 101900,
 135913,
 130379,
 12359,
 71418,
 71484,
 82670,
 13542,
 67131,
 41234,
 141947,
 78910,
 86937,
 43326,
 16261,
 190713,
 67149,
 95349,
 106092,
 149677,
 167289,
 60969,
 117134,
 182546,
 210892,
 17187,
 184283,
 92817,
 6633,
 111802,
 176790,
 239754,
 69028,
 203842,
 80825,
 234825,
 136091,
 208503,
 101020,
 243596,
 154392,
 66380,
 214815,
 155108,
 99571,
 61069,
 25666,
 12393,
 29849,
 146049,
 92496,
 149883,
 131749,
 66506,
 114656,
 32285,
 141990,
 144005,
 174030,
 117764,
 216368,
 228727,
 237863,
 203077,
 178571,
 56844,
 116029,
 98438,
 235805,
 29626,
 176471,
 153641,
 8322,
 9883,
 171631,
 94790,
 116667,
 179690,
 73808,
 238590,
 172258,
 128186,
 25732,
 117620,
 195783,
 239448,
 25810,
 77917,
 90495,
 119697,
 26253,
 147555,
 101031,
 183910,
 195597,
 210409,
 227749,
 150162,
 217847,
 205196,
 78276,
 21809,
 48236,
 57319,
 141884,
 120736,
 143330,
 30485,
 148761,
 2563,
 44321,
 79013,
 41569,
 51749,
 119427,
 2340,
 201747,
 194736,
 113490,
 62159,
 194323,
 119945,
 795,
 189828,
 197565,
 45179,
 99255,
 32333,
 3560,
 242032,
 141401,
 54244,
 215628,
 27735,
 221236,
 170519,
 113007,
 71280,
 231057,
 127622,
 133328,
 38892,
 53081,
 170760,
 17797,
 189907,
 133066,
 165477,
 166473,
 243742,
 1941,
 146833,
 236585,
 202719,
 159247,
 212889,
 152659,
 208123,
 38122,
 193694,
 93589,
 234462,
 204047,
 176980,
 31784,
 117631,
 136853,
 195399,
 31672,
 12866,
 145596,
 66915,
 196158,
 222598,
 50207,
 98905,
 1027,
 24958,
 48745,
 79992,
 143803,
 44,
 54674,
 19217,
 182772,
 126192,
 214239,
 144883,
 76681,
 150224,
 50137,
 79390,
 200550,
 15906,
 145368,
 163298,
 25337,
 173544,
 92947,
 116369,
 191240,
 226027,
 72229,
 185423,
 67175,
 108639,
 94049,
 37543,
 56884,
 202537,
 204481,
 221041,
 212497,
 43757,
 76475,
 203192,
 62435,
 197660,
 82825,
 10791,
 107192,
 161753,
 232305,
 122769,
 212050,
 163776,
 90603,
 146742,
 198314,
 234685,
 15501,
 12479,
 201667,
 72738,
 89605,
 32986,
 201343,
 133333,
 160124,
 3066,
 13981,
 209281,
 102196,
 140044,
 40287,
 93585,
 94562,
 27053,
 39872,
 13630,
 47789,
 83149,
 209028,
 65634,
 186771,
 34427,
 243745,
 37223,
 192126,
 32989,
 194198,
 210085,
 234691,
 142070,
 90840,
 16140,
 61906,
 68379,
 19349,
 166767,
 229769,
 232695,
 126890,
 86788,
 65075,
 166805,
 11673,
 160608,
 3963,
 35982,
 44266,
 214060,
 172783,
 119284,
 87050,
 24542,
 184867,
 234167,
 18364,
 64602,
 124516,
 123383,
 209333,
 8804,
 177829,
 40646,
 166249,
 183508,
 168526,
 107218,
 177657,
 98626,
 96186,
 163586,
 71919,
 256,
 167745,
 178757,
 161131,
 110222,
 243740,
 138063,
 135505,
 59878,
 4362,
 120553,
 43414,
 61834,
 90562,
 88152,
 19102,
 204209,
 73846,
 210763,
 14117,
 36596,
 12615,
 87830,
 205513,
 29002,
 128012,
 58570,
 98080,
 16885,
 197665,
 198781,
 45413,
 244305,
 211391,
 60106,
 231999,
 110306,
 26774,
 211419,
 180949,
 73048,
 106570,
 82660,
 143959,
 52918,
 30205,
 103834,
 194222,
 150290,
 205189,
 182067,
 89516,
 39659,
 68268,
 212268,
 158860,
 155623,
 10653,
 216518,
 37229,
 89384,
 41612,
 33862,
 194194,
 58236,
 16131,
 97209,
 183001,
 35874,
 173019,
 132694,
 106625,
 66160,
 88962,
 147374,
 245919,
 100030,
 97217,
 40215,
 227057,
 37790,
 27829,
 113331,
 84562,
 72179,
 212318,
 131888,
 231874,
 83294,
 44351,
 90844,
 117965,
 102311,
 173623,
 198622,
 139028,
 143928,
 115745,
 202038,
 142800,
 129732,
 117,
 14491,
 96855,
 23920,
 194805,
 132924,
 106201,
 217365,
 98014,
 83361,
 236991,
 146233,
 161107,
 224548,
 18967,
 46490,
 32043,
 198591,
 40076,
 115133,
 3954,
 163574,
 241091,
 86574,
 194691,
 226747,
 134098,
 81278,
 120104,
 48597,
 8479,
 116010,
 126876,
 56197,
 140756,
 105050,
 122889,
 89406,
 89784,
 95991,
 220138,
 193412,
 234905,
 234320,
 57703,
 136129,
 99315,
 29807,
 73453,
 140486,
 50318,
 121442,
 31902,
 27895,
 45448,
 118093,
 224672,
 107698,
 128244,
 228302,
 189780,
 77265,
 156712,
 111569,
 212801,
 217493,
 90859,
 169288,
 163986,
 226522,
 190557,
 77406,
 11359,
 115865,
 219524,
 172899,
 11537,
 166431,
 60743,
 98709,
 191918,
 83729,
 113354,
 9199,
 172186,
 34304,
 82434,
 1189,
 78081,
 57842,
 61112,
 234572,
 12616,
 199604,
 56110,
 225629,
 76858,
 151657,
 92633,
 65707,
 204015,
 188016,
 135428,
 157302,
 49012,
 127248,
 166841,
 152427,
 155246,
 90366,
 230819,
 114318,
 44839,
 146321,
 128570,
 181667,
 25719,
 188845,
 49955,
 212105,
 7117,
 321,
 209651,
 236007,
 168250,
 211330,
 5693,
 128601,
 148006,
 184194,
 140365,
 37184,
 19254,
 164591,
 211558,
 41579,
 186350,
 52407,
 4560,
 23189,
 788,
 93764,
 176714,
 56656,
 91524,
 149726,
 32339,
 191193,
 38120,
 238259,
 115536,
 62956,
 79798,
 231280,
 11942,
 118909,
 99810,
 97626,
 60729,
 168863,
 94174,
 75091,
 148426,
 48381,
 153855,
 126645,
 38673,
 41955,
 155837,
 167789,
 150034,
 83439,
 219799,
 245134,
 211152,
 174607,
 172673,
 192982,
 159728,
 81134,
 176322,
 81822,
 118924,
 172551,
 178145,
 241118,
 146374,
 8599,
 193866,
 197984,
 108772,
 93871,
 35973,
 181023,
 128290,
 229570,
 19953,
 175475,
 223615,
 3016,
 41544,
 114021,
 196677,
 41827,
 6542,
 142203,
 244909,
 17081,
 90064,
 226988,
 116020,
 39115,
 89214,
 195374,
 201561,
 202055,
 111334,
 172289,
 152209,
 69588,
 172530,
 91340,
 210066,
 170617,
 94017,
 79567,
 192134,
 101720,
 139601,
 122314,
 71382,
 2712,
 7319,
 227018,
 151361,
 181099,
 187831,
 1185,
 1398,
 133308,
 241953,
 59920,
 94207,
 136113,
 203644,
 17856,
 167042,
 232712,
 151656,
 237969,
 115601,
 211639,
 194821,
 118805,
 197481,
 151789,
 243090,
 158426,
 99047,
 221672,
 191699,
 88539,
 204356,
 51788,
 47069,
 88680,
 80644,
 58435,
 59774,
 160983,
 128781,
 232282,
 153760,
 144139,
 40275,
 237351,
 139455,
 29099,
 118332,
 53645,
 32312,
 45305,
 172727,
 206920,
 196361,
 40652,
 33092,
 48118,
 124053,
 33006,
 22887,
 23642,
 209080,
 209801,
 16741,
 18597,
 18813,
 137865,
 223883,
 140093,
 10605,
 135229,
 87543,
 173632,
 146490,
 236058,
 32896,
 187876,
 96807,
 171490,
 201803,
 89905,
 230427,
 176184,
 139553,
 121498,
 185540,
 53181,
 102680,
 19038,
 86410,
 128113,
 219258,
 155849,
 139928,
 142340,
 65080,
 233626,
 8492,
 ...]

In [13]:
def separar_treino(x, df_treino):
    if x.name in df_treino.index:
        return True
    else:
        return False

df_treino = df.sample(frac=0.7, random_state=42)
df['Flag_Treino'] = df.apply(lambda x: separar_treino(x, df_treino), axis=1)
df['Flag_Treino'].value_counts()

True     172206
False     73802
Name: Flag_Treino, dtype: int64

## Salvando os datasets

In [14]:
os.makedirs('./bases', exist_ok=True)  

df.to_csv('./bases/application_splitado_07.csv', index=False)